[[redirects]]
  from = "/api/*"
  to = "http://3.107.237.223:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/verify"
  to = "https://face-verification-service-latest.onrender.com/verify"
  status = 200
  force = true
